[package]
name = "rusqlite-derive-impl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macro implementation for rusqlite-derive"

[lib]
proc-macro = true

[dependencies]
attribute-derive = "0.10.5"
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = "2.0.117"
