[package]
name = "rusqlite-derive"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[features]
default = []
bundled = ["rusqlite/bundled"]

[dependencies]
rusqlite = { version = "0.40.2", default-features = false }
rusqlite-derive-impl = { version = "=0.1.0", path = "../impl" }

[dev-dependencies]
rusqlite = { version = "0.40.2", default-features = false, features = ["bundled"] }
trybuild = "1"
