//! Derive-based row mapping for [rusqlite](https://docs.rs/rusqlite).
//!
//! Deriving [`RusqliteFetch`] adds two helpers to a struct: [`fetch`](RusqliteFetch::fetch)
//! returns every row from a configured SQL source, while
//! [`fetch_with_filter`](RusqliteFetch::fetch_with_filter) appends an expression
//! after `WHERE`. This crate is a convenience layer for reads, not a full ORM.
//!
//! # Example
//!
//! ```
//! use rusqlite::Connection;
//! use rusqlite_derive::RusqliteFetch;
//!
//! #[derive(Debug, PartialEq, RusqliteFetch)]
//! #[rusqlite(from = "users")]
//! struct User {
//!     id: i64,
//!     name: String,
//! }
//!
//! let conn = Connection::open_in_memory()?;
//! conn.execute_batch(
//!     "CREATE TABLE users (id INTEGER, name TEXT);
//!      INSERT INTO users VALUES (1, 'Ada'), (2, 'Grace');",
//! )?;
//!
//! let users = User::fetch(&conn)?;
//! let ada = User::fetch_with_filter(&conn, "name = 'Ada'")?;
//!
//! assert_eq!(users.len(), 2);
//! assert_eq!(ada, vec![User { id: 1, name: "Ada".into() }]);
//! # Ok::<(), rusqlite::Error>(())
//! ```
//!
//! # Mapping attributes
//!
//! - `#[rusqlite(from = "...")]` replaces the struct's complete SQL `FROM`
//!   fragment.
//! - `#[rusqlite(select = "...")]` replaces a field's select expression.
//! - `#[rusqlite(default)]` omits a field from the query and initializes it with
//!   [`Default::default`]. It cannot be combined with `select`.
//!
//! Attribute values are SQL fragments, so they may contain qualified columns,
//! expressions, aliases, and joins. Tuple structs require an explicit `select`
//! expression on every non-default field. Generic, fieldless, and unit structs
//! are also supported. See the [`RusqliteFetch`] derive for full details.
//!
//! # Filtering safely
//!
//! [`RusqliteFetch::fetch_with_filter`] inserts its argument verbatim. Never
//! include untrusted input in the filter. Use rusqlite placeholders and bound
//! parameters for dynamic values.

pub use rusqlite_derive_impl::RusqliteFetch;

/// Fetches values of a struct from SQLite.
///
/// Implementations are normally generated by
/// [`#[derive(RusqliteFetch)]`](derive@RusqliteFetch). The derive selects fields
/// in declaration order and decodes them with [`rusqlite::Row::get`]. A field
/// marked `#[rusqlite(default)]` is omitted from the query and initialized with
/// [`Default::default`].
///
/// Use rusqlite directly for writes, bound parameters, custom result handling,
/// or incremental row processing.
pub trait RusqliteFetch: Sized {
    /// Fetches every row from the derive's configured `FROM` fragment.
    ///
    /// The generated statement has the form `SELECT <fields> FROM <source>;`.
    fn fetch(conn: &rusqlite::Connection) -> rusqlite::Result<Vec<Self>>;

    /// Fetches rows matching a SQL expression appended after `WHERE`.
    ///
    /// `filter` may include clauses that can follow a `WHERE` expression, such
    /// as `ORDER BY` or `LIMIT`.
    ///
    /// # Security
    ///
    /// The generated implementation inserts `filter` verbatim; it neither
    /// escapes values nor binds parameters. Only pass fragments controlled
    /// entirely by the application. Use rusqlite directly for dynamic values.
    fn fetch_with_filter(conn: &rusqlite::Connection, filter: &str) -> rusqlite::Result<Vec<Self>>;
}
